import { cors, admin, user, ok, fail, requestId, text } from "../_shared/core.ts";
const OPENAI_API_KEY=Deno.env.get("OPENAI_API_KEY")??"";
Deno.serve(async(req:Request)=>{const id=requestId();if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return fail("method_not_allowed","POST required",id,405);try{
  const u=await user(req);const body=await req.json();const filename=text(body.filename).trim(),raw=text(body.raw_text).trim();
  if(!filename||filename.length>255||raw.length<50||raw.length>100000)return fail("invalid_request","filename or raw_text is invalid",id,400);
  let parsed={contact:{name:"",email:null,phone:null,location:""},summary:"",skills:[],education:[],experience:[],certifications:[],languages:[]};let usage={prompt_tokens:0,completion_tokens:0,total_tokens:0};
  if(OPENAI_API_KEY){const ai=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{authorization:`Bearer ${OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-4o-mini",response_format:{type:"json_object"},temperature:0,messages:[{role:"system",content:"Extract a resume into strict JSON with contact{name,email,phone,location}, summary, skills[], education[{institution,credential,field,start_date,end_date}], experience[{company,title,start_date,end_date,highlights[]}], certifications[], languages[]. Never invent facts."},{role:"user",content:raw}]})});if(!ai.ok)throw new Error(`OpenAI ${ai.status}`);const j=await ai.json();parsed=JSON.parse(j.choices[0].message.content);usage=j.usage??usage;}
  const db=admin();let q=body.replace_resume_id?db.from("resumes").update({filename,raw_text:raw,parsed,status:"parsed"}).eq("id",body.replace_resume_id).eq("user_id",u.id).select("id,filename,status,parsed,created_at").single():db.from("resumes").insert({user_id:u.id,filename,raw_text:raw,parsed,status:"parsed"}).select("id,filename,status,parsed,created_at").single();const {data,error}=await q;if(error)throw error;
  if(usage.total_tokens)await db.from("ai_usage_logs").insert({user_id:u.id,function_name:"parse-resume",model:"gpt-4o-mini",prompt_tokens:usage.prompt_tokens,completion_tokens:usage.completion_tokens,total_tokens:usage.total_tokens});
  return ok({resume:data,tokens_used:{prompt:usage.prompt_tokens,completion:usage.completion_tokens,total:usage.total_tokens}},id);
}catch(e){const m=e instanceof Error?e.message:String(e);return fail(m==="unauthenticated"?"unauthenticated":"internal_error",m,id,m==="unauthenticated"?401:500);}});
