-- REVIEW GATE: do not run until Steven approves the Phase A list.
-- URLs were checked on 2026-09-04. `pending` means the site rejected a plain
-- HTTP client and still requires the Phase B Playwright verification pass.

insert into public.priority_employers
  (company_name,country,gta_relevance,industry,career_url,ats_type,crawl_strategy,priority_tier,verify_status,last_success_at,last_apply_url,notes)
values
  ('Royal Bank of Canada','CA','high','Banking','https://jobs.rbc.com/ca/en','workday','playwright_click',1,'verified',null,null,'RBC; BA, operations, policy and research roles; career URL HTTP 200.'),
  ('TD Bank Group','CA','high','Banking','https://careers.td.com/','workday','playwright_click',1,'verified',null,null,'Toronto-based; BA, operations and strategy internships; career URL HTTP 200.'),
  ('Scotiabank','CA','high','Banking','https://jobs.scotiabank.com/','custom','playwright_click',1,'verified',null,null,'Toronto-based; analytics, operations and public-affairs fit; career URL HTTP 200.'),
  ('Bank of Montreal','CA','high','Banking','https://jobs.bmo.com/ca/en','workday','playwright_click',1,'verified',null,null,'Major GTA employer; business and operations internships; career URL HTTP 200.'),
  ('CIBC','CA','high','Banking','https://www.cibc.com/en/about-cibc/careers.html','custom','playwright_click',1,'verified',null,null,'Toronto-based; BA and operations roles; official career URL HTTP 200.'),
  ('Sun Life','CA','high','Insurance','https://www.sunlife.com/en/careers/','workday','playwright_click',1,'verified',null,null,'GTA/Kitchener presence; business, research and operations roles; HTTP 200.'),
  ('Manulife','CA','high','Insurance','https://careers.manulife.com/','workday','playwright_click',1,'pending',null,null,'Toronto-based; browser verification required because plain HTTP returned 403.'),
  ('Canada Life','CA','medium','Insurance','https://jobs.canadalife.com/','workday','playwright_click',2,'verified',null,null,'Ontario roles in operations and analytics; career URL HTTP 200.'),
  ('OMERS','CA','high','Pensions and Investment','https://www.omers.com/careers','workday','playwright_click',1,'verified',null,null,'Toronto-based; investment operations, research and strategy; HTTP 200.'),
  ('Ontario Teachers'' Pension Plan','CA','high','Pensions and Investment','https://www.otpp.com/en-ca/careers/','workday','playwright_click',1,'verified',null,null,'Toronto-based; research, investment operations and strategy; HTTP 200.'),
  ('CPP Investments','CA','high','Pensions and Investment','https://www.cppinvestments.com/careers/','workday','playwright_click',1,'verified',null,null,'Toronto-based; research, analytics and operations; career URL HTTP 202.'),
  ('McKinsey & Company Canada','CA','high','Consulting','https://www.mckinsey.com/ca/careers','custom','playwright_click',1,'pending',null,null,'Toronto office and business analyst path; browser verification required after HTTP timeout.'),
  ('Boston Consulting Group Canada','CA','high','Consulting','https://careers.bcg.com/global/en/','custom','playwright_click',1,'verified',null,null,'Toronto office; consulting and research roles; career URL HTTP 200.'),
  ('Bain & Company Canada','CA','high','Consulting','https://www.bain.com/careers/','custom','playwright_click',1,'verified',null,null,'Toronto office; associate consultant and research fit; HTTP 200.'),
  ('Deloitte Canada','CA','high','Consulting','https://careers.deloitte.ca/','custom','playwright_click',1,'verified',null,null,'Large GTA footprint; BA, operations and public-sector consulting; HTTP 200.'),
  ('PwC Canada','CA','high','Consulting','https://www.pwc.com/ca/en/careers.html','workday','playwright_click',1,'verified',null,null,'Large GTA footprint; advisory, operations and research roles; HTTP 200.'),
  ('EY Canada','CA','high','Consulting','https://www.ey.com/en_ca/careers','workday','playwright_click',1,'verified',null,null,'Large GTA footprint; consulting and business roles; HTTP 200.'),
  ('KPMG Canada','CA','high','Consulting','https://kpmg.com/ca/en/careers.html','workday','playwright_click',1,'verified',null,null,'Large GTA footprint; advisory, research and operations roles; HTTP 200.'),
  ('Bell Canada','CA','high','Telecommunications','https://jobs.bce.ca/bell/','custom','playwright_click',1,'verified',null,null,'Major GTA employer; marketing, strategy, policy and operations; HTTP 200.'),
  ('Rogers Communications','CA','high','Telecommunications','https://jobs.rogers.com/','custom','playwright_click',1,'verified',null,null,'Toronto-based; marketing, analytics and operations; HTTP 200.'),
  ('TELUS','CA','high','Telecommunications','https://www.telus.com/en/about/careers','workday','playwright_click',1,'pending',null,null,'GTA/Canada roles; browser verification required because plain HTTP returned 403.'),
  ('TMX Group','CA','high','Financial Markets','https://www.tmx.com/en/careers','workday','playwright_click',1,'verified',null,null,'Toronto-based; market research, operations and corporate roles; HTTP 200.'),
  ('Loblaw Companies','CA','high','Retail','https://careers.loblaw.ca/','workday','playwright_click',1,'verified',null,null,'Brampton/Toronto footprint; analytics, merchandising and operations; HTTP 200.'),
  ('Canadian Tire Corporation','CA','high','Retail','https://corp.canadiantire.ca/English/careers/default.aspx','workday','playwright_click',1,'pending',null,null,'Toronto-based; strategy, marketing and operations; browser verification required after HTTP 403.'),
  ('Walmart Canada','CA','high','Retail','https://careers.walmart.ca/','workday','playwright_click',1,'verified',null,null,'Mississauga-based; merchandising, analytics and operations; HTTP 200.'),
  ('Hydro One','CA','high','Utilities','https://jobs.hydroone.com/','custom','playwright_click',1,'verified',null,null,'Toronto/Ontario; business analyst, planning and public-affairs fit; HTTP 200.'),
  ('Toronto Hydro','CA','high','Utilities','https://www.torontohydro.com/careers','custom','playwright_click',1,'verified',null,null,'Toronto utility; operations, policy and customer research; HTTP 200.'),
  ('Ontario Power Generation','CA','high','Utilities','https://jobs.opg.com/','custom','playwright_click',1,'verified',null,null,'GTA/Ontario; business, planning and stakeholder roles; HTTP 200.'),
  ('Metrolinx','CA','high','Public Transportation','https://www.metrolinx.com/en/about-us/careers','custom','playwright_click',1,'verified',null,null,'GTA public agency; planning, operations, research and public affairs; HTTP 200.'),
  ('City of Toronto','CA','high','Government','https://jobs.toronto.ca/jobsatcity/','custom','playwright_click',1,'verified',null,null,'Direct public-policy, operations and research relevance; HTTP 200.'),
  ('Apple','US','low','Technology','https://jobs.apple.com/en-us/search','custom','playwright_click',1,'verified',null,null,'Steven-named target; business operations, marketing and government affairs; HTTP 200.'),
  ('IBM','US','medium','Technology and Consulting','https://www.ibm.com/careers/search','custom','playwright_click',1,'verified',null,null,'Steven-named target; consulting, operations and market roles; HTTP 200.'),
  ('Capital One','US','low','Financial Services','https://www.capitalonecareers.com/','custom','playwright_click',1,'verified',null,null,'Steven-named target; business analyst and strategy internships; HTTP 200.'),
  ('Microsoft','US','medium','Technology','https://apply.careers.microsoft.com/careers','custom','playwright_click',1,'verified',null,null,'Business programs, operations, marketing and public affairs; HTTP 200.'),
  ('Amazon','US','medium','Technology and Retail','https://www.amazon.jobs/en/search','custom','playwright_click',1,'verified',null,null,'Pathways, operations, vendor and business analyst roles; HTTP 200.'),
  ('Google','US','medium','Technology','https://www.google.com/about/careers/applications/jobs/results/','custom','playwright_click',1,'verified',null,null,'Business, strategy, policy and marketing roles; HTTP 200.'),
  ('Meta','US','low','Technology','https://www.metacareers.com/jobsearch/','custom','playwright_click',2,'verified',null,null,'Operations, policy, research and marketing roles; HTTP 200.'),
  ('Salesforce','US','medium','Enterprise Software','https://www.salesforce.com/company/careers/jobs/','workday','playwright_click',2,'verified',null,null,'Business operations, strategy and marketing roles; HTTP 200.'),
  ('Adobe','US','medium','Software','https://careers.adobe.com/us/en/search-results','workday','playwright_click',2,'verified',null,null,'Product marketing, research and business operations; HTTP 200.'),
  ('Cisco','US','medium','Networking Technology','https://careers.cisco.com/global/en','custom','playwright_click',2,'verified',null,null,'Business analyst, operations and marketing programs; HTTP 200.'),
  ('Visa','US','medium','Payments','https://corporate.visa.com/en/careers.html','custom','playwright_click',1,'verified',null,null,'Strategy, client operations, research and government engagement; HTTP 200.'),
  ('Mastercard','US','medium','Payments','https://careers.mastercard.com/us/en','workday','playwright_click',1,'verified',null,null,'Strategy, operations, economics and public-policy roles; HTTP 200.'),
  ('American Express','US','medium','Financial Services','https://www.americanexpress.com/en-us/careers/','custom','playwright_click',1,'verified',null,null,'Strategy, marketing, operations and analytics programs; HTTP 200.'),
  ('JPMorgan Chase','US','medium','Banking','https://www.jpmorganchase.com/careers','custom','playwright_click',1,'verified',null,null,'Corporate analyst, operations and research programs; HTTP 200.'),
  ('Bank of America','US','medium','Banking','https://careers.bankofamerica.com/en-us/job-search','custom','playwright_click',1,'verified',null,null,'Business, operations and market research programs; HTTP 200.'),
  ('Citi','US','medium','Banking','https://jobs.citi.com/search-jobs','custom','playwright_click',1,'verified',null,null,'Operations, business and public-affairs roles; HTTP 200.'),
  ('Accenture','US','medium','Consulting','https://www.accenture.com/us-en/careers/jobsearch','workday','playwright_click',1,'verified',null,null,'Strategy, consulting and operations internships; HTTP 200.'),
  ('Gartner','US','low','Research and Advisory','https://jobs.gartner.com/search-jobs','workday','playwright_click',2,'pending',null,null,'Direct market-research and advisory relevance; browser verification required after HTTP 403.'),
  ('NielsenIQ','US','medium','Market Research','https://nielseniq.com/global/en/careers/','workday','playwright_click',1,'verified',null,null,'Direct consumer and market-research relevance; HTTP 200.'),
  ('Procter & Gamble','US','medium','Consumer Goods','https://www.pgcareers.com/global/en/search-results','workday','playwright_click',1,'verified',null,null,'Brand, consumer insights, sales operations and strategy; HTTP 200.')
on conflict do nothing;
