-- Each endpoint was probed on 2026-09-02 and returned HTTP 200 with a non-empty
-- JSON job array containing at least one Canada/GTA-relevant posting.
insert into public.job_sources (ats_type, company_name, board_token, board_url, enabled)
values
  ('ashby','KOHO','koho','https://api.ashbyhq.com/posting-api/job-board/koho',true),
  ('greenhouse','StackAdapt','stackadapt','https://boards-api.greenhouse.io/v1/boards/stackadapt/jobs?content=true',true),
  ('greenhouse','Geotab','geotab','https://boards-api.greenhouse.io/v1/boards/geotab/jobs?content=true',true),
  ('lever','PointClickCare','pointclickcare','https://api.lever.co/v0/postings/pointclickcare?mode=json',true),
  ('lever','Caseware','caseware','https://api.lever.co/v0/postings/caseware?mode=json',true),
  ('ashby','Loopio','loopio','https://api.ashbyhq.com/posting-api/job-board/loopio',true),
  ('ashby','Relay Financial','relayfi','https://api.ashbyhq.com/posting-api/job-board/relayfi',true),
  ('ashby','Cohere','cohere','https://api.ashbyhq.com/posting-api/job-board/cohere',true),
  ('greenhouse','Lyft','lyft','https://boards-api.greenhouse.io/v1/boards/lyft/jobs?content=true',true),
  ('greenhouse','Stripe','stripe','https://boards-api.greenhouse.io/v1/boards/stripe/jobs?content=true',true),
  ('greenhouse','Datadog','datadog','https://boards-api.greenhouse.io/v1/boards/datadog/jobs?content=true',true),
  ('greenhouse','Okta','okta','https://boards-api.greenhouse.io/v1/boards/okta/jobs?content=true',true),
  ('greenhouse','MongoDB','mongodb','https://boards-api.greenhouse.io/v1/boards/mongodb/jobs?content=true',true),
  ('greenhouse','Coursera','coursera','https://boards-api.greenhouse.io/v1/boards/coursera/jobs?content=true',true),
  ('greenhouse','Twilio','twilio','https://boards-api.greenhouse.io/v1/boards/twilio/jobs?content=true',true),
  ('ashby','Snowflake','snowflake','https://api.ashbyhq.com/posting-api/job-board/snowflake',true),
  ('greenhouse','Asana','asana','https://boards-api.greenhouse.io/v1/boards/asana/jobs?content=true',true),
  ('greenhouse','Figma','figma','https://boards-api.greenhouse.io/v1/boards/figma/jobs?content=true',true),
  ('ashby','Notion','notion','https://api.ashbyhq.com/posting-api/job-board/notion',true),
  ('ashby','Plaid','plaid','https://api.ashbyhq.com/posting-api/job-board/plaid',true),
  ('greenhouse','Scale AI','scaleai','https://boards-api.greenhouse.io/v1/boards/scaleai/jobs?content=true',true),
  ('ashby','OpenAI','openai','https://api.ashbyhq.com/posting-api/job-board/openai',true),
  ('greenhouse','Anthropic','anthropic','https://boards-api.greenhouse.io/v1/boards/anthropic/jobs?content=true',true),
  ('greenhouse','Airtable','airtable','https://boards-api.greenhouse.io/v1/boards/airtable/jobs?content=true',true),
  ('greenhouse','Dropbox','dropbox','https://boards-api.greenhouse.io/v1/boards/dropbox/jobs?content=true',true),
  ('greenhouse','Pinterest','pinterest','https://boards-api.greenhouse.io/v1/boards/pinterest/jobs?content=true',true),
  ('greenhouse','Instacart','instacart','https://boards-api.greenhouse.io/v1/boards/instacart/jobs?content=true',true),
  ('greenhouse','Coinbase','coinbase','https://boards-api.greenhouse.io/v1/boards/coinbase/jobs?content=true',true),
  ('ashby','Vanta','vanta','https://api.ashbyhq.com/posting-api/job-board/vanta',true),
  ('greenhouse','Vercel','vercel','https://boards-api.greenhouse.io/v1/boards/vercel/jobs?content=true',true),
  ('greenhouse','Reddit','reddit','https://boards-api.greenhouse.io/v1/boards/reddit/jobs?content=true',true),
  ('greenhouse','Affirm','affirm','https://boards-api.greenhouse.io/v1/boards/affirm/jobs?content=true',true),
  ('greenhouse','Robinhood','robinhood','https://boards-api.greenhouse.io/v1/boards/robinhood/jobs?content=true',true),
  ('greenhouse','Brex','brex','https://boards-api.greenhouse.io/v1/boards/brex/jobs?content=true',true),
  ('greenhouse','Webflow','webflow','https://boards-api.greenhouse.io/v1/boards/webflow/jobs?content=true',true),
  ('greenhouse','Databricks','databricks','https://boards-api.greenhouse.io/v1/boards/databricks/jobs?content=true',true),
  ('ashby','Confluent','confluent','https://api.ashbyhq.com/posting-api/job-board/confluent',true),
  ('greenhouse','GitLab','gitlab','https://boards-api.greenhouse.io/v1/boards/gitlab/jobs?content=true',true),
  ('greenhouse','Canonical','canonical','https://boards-api.greenhouse.io/v1/boards/canonical/jobs?content=true',true),
  ('greenhouse','PagerDuty','pagerduty','https://boards-api.greenhouse.io/v1/boards/pagerduty/jobs?content=true',true),
  ('greenhouse','Amplitude','amplitude','https://boards-api.greenhouse.io/v1/boards/amplitude/jobs?content=true',true),
  ('greenhouse','Braze','braze','https://boards-api.greenhouse.io/v1/boards/braze/jobs?content=true',true)
on conflict (ats_type, board_token) do update set
  company_name=excluded.company_name,
  board_url=excluded.board_url,
  enabled=true,
  updated_at=now();
